### ISSUE TITLE
fails if adapter is not yet defined

### ISSUE THREAD

**Issue by gmarinov** [otalk/attachMediaStream#18]
https://github.com/otalk/attachMediaStream/blob/764a4c663d0636b3256ce657fd30786f5c1c8ee0/attachmediastream.js#L39

... and takes away the rtc stack with it

**Comment by fippo** [comment]
whoops... fixed in 2.0.2

(the lack of linting on this repository...)

**Comment by gmarinov** [comment]
yep, seems to work now.
